services:
  nginx:
    image: nginx:latest
    container_name: nginx_test
    ports:
      - "82:82"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend-client:/usr/share/nginx/html
      - ./frontend-admin:/var/www/frontend-admin
      - ./uploads:/usr/share/nginx/html/assets
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge